sudo: required
services:
  - docker

  before_install:
    - docker build -t absoluteun1t/docker-react -f Dockerfile.dev .

  script:
    - docker run absoluteun1t/docker-react npm run test -- --coverage
